<?php
namespace jarekkozak\util;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-06 at 09:02:59.
 */
class BankAccountNumberTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BankAccountNumber
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BankAccountNumber('PL61109010140000071219812874E');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testVerify(){
        $this->assertFalse($this->object->Verify('PL61109010140000071219812874E'));
    }
    
    public function testVerify1(){
        $this->assertTrue($this->object->Verify('PL61109010140000071219812874'));
    }
    
    public function testVerify11(){
        $this->assertTrue($this->object->Verify('PL 611090 1014 0000 0712 1981 2874'));
    }

    public function testVerify2(){
        $this->assertFalse($this->object->Verify('61109010140000071219812874'));
    }
    
}
