<?php
namespace jarekkozak\util;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-06 at 09:09:04.
 */
class BankAccountNumberCountryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BankAccountNumberCountry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BankAccountNumberCountry('pl');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testExample(){
        $ret = 'IBAN:'.$this->object->IBANExample();
    }

    public function testExampleDomestic(){
        $ret = 'DOMESTIC:'.$this->object->DomesticExample();
    }

    public function testExampleBBan(){
        $ret = 'BBAN:'.$this->object->BBANExample();
    }
    
}
