<?php

namespace jarekkozak\sys;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-31 at 08:37:49.
 */
class DependencyManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DependencyManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jk\sys\DependencyManager::register
     */
    public function testRegister()
    {
        \Yii::$container->clear('jarekkozak\sys\IProperties');
        DependencyManager::register([
            'jarekkozak\sys\IProperties' => [
                'class' => 'jarekkozak\sys\PropertiesFile',
                'filename' => dirname(__FILE__).'/PropertiesFileTest.properties'
        ]]);

        $a = \Yii::$container->get('jarekkozak\sys\TestDPM');
        self::assertInstanceOf('jarekkozak\sys\PropertiesFile', $a->prop);
    }

    /**
     * @covers jk\sys\DependencyManager::register
     */
    public function testRegister1()
    {
        \Yii::$container->clear('jarekkozak\sys\IProperties');
        DependencyManager::register([
            'jarekkozak\sys\IProperties' => [
                'class' => 'jarekkozak\sys\Properties',
        ]]);
        $container = \Yii::$container;
        self::assertTrue(\Yii::$container->has('jarekkozak\sys\IProperties'));

        $a = \Yii::$container->get('jarekkozak\sys\TestDPM');
        self::assertInstanceOf('jarekkozak\sys\Properties', $a->prop);
    }

    /**
     * @covers jk\sys\DependencyManager::register
     */
    public function testRegister2()
    {
        \Yii::$container->clear('jarekkozak\sys\IProperties');
        DependencyManager::register([
            'jarekkozak\sys\IProperties' => function() {
                return new \jarekkozak\sys\Properties(['values' => ['prop1' => 'test1']]);
            }]);
            $a = \Yii::$container->get('jarekkozak\sys\TestDPM');
            self::assertInstanceOf('jarekkozak\sys\Properties', $a->prop);
            self::assertEquals('test1', $a->prop->getProperty('prop1'));
    }
}

class TestDPM
{
    public $prop;

    public function __construct(\jarekkozak\sys\IProperties $_prop)
    {
        $this->prop = $_prop;
    }
}