<?php

namespace jarekkozak\kie\heartbeat;

use jarekkozak\kie\KieClient;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-06 at 09:33:25.
 */
class KieHBTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var KieHB
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jarekkozak\kie\heartbeat\KieHB::listenHeart
     */
    public function testListenHeart()
    {
        $client = new KieClient([
            'context' => 'http://localhost:8081/kie-server',
            'username' => 'kiesrv',
            'password' => 'kiesrv',
        ]);
        $hb = new KieHB([
            'client' => $client,
        ]);
        $this->assertTrue($hb->listenHeart());
    }

    /**
     * @covers jarekkozak\kie\heartbeat\KieHB::getHeartBeat
     */
    public function testGetHeartBeat()
    {
        $client = new KieClient([
            'context' => 'http://localhost:8081/kie-server',
            'username' => 'kiesrv',
            'password' => 'kiesrv',
        ]);
        $hb = new KieHB([
            'client' => $client,
        ]);
        $res = $hb->getHeartBeat();
        $this->assertCount(2,$res);
    }




}