<?php

namespace jarekkozak\dict;

use jarekkozak\tests\dict\Dict1;
use jarekkozak\tests\dict\Dict1Translator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-26 at 12:22:48.
 * @coversDefaultClass jarekkozak\dict\DictionaryJsonDecorator
 */
class DictionaryJsonDecoratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DictionaryJsonDecorator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers ::values
     */
    public function testValues()
    {
        $comp = '[{"id":1,"text":"com.common.value1"},{"id":2,"text":"com.common.value2"}]';
        $decorator = new DictionaryJsonDecorator();
        self::assertEquals($comp, $decorator->values(Dict1::getInstance()->values()));
    }

    /**
     * With translation
     * @covers ::values
     */
    public function testValuesTrans()
    {
        $comp = '[{"id":1,"text":"com.common.value1-TRANSLATED-jarekkozak\\\tests\\\dict\\\Dict1"},{"id":2,"text":"com.common.value2-TRANSLATED-jarekkozak\\\tests\\\dict\\\Dict1"}]';
        $decorator = new DictionaryJsonDecorator(new Dict1Translator());
        self::assertEquals($comp, $decorator->values(Dict1::getInstance()->values()));
    }
}