<?php

namespace jarekkozak\dict;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-25 at 22:23:54.
 */
class DictionaryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Dictionary
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jarekkozak\dict\Dictionary::value
     * @todo   Implement testValue().
     */
    public function testValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jarekkozak\dict\Dictionary::equals
     * @todo   Implement testEquals().
     */
    public function testEquals()
    {
        $a = new \jarekkozak\tests\dict\Dict1(\jarekkozak\tests\dict\Dict1::VALUE1);
        $b = new \jarekkozak\tests\dict\Dict1(\jarekkozak\tests\dict\Dict1::VALUE1);
        $this->assertTrue($a->equals($b));
        $this->assertTrue($a == $b);
        $this->assertTrue(1 == $b);

        $a = new \jarekkozak\tests\dict\Dict1(\jarekkozak\tests\dict\Dict1::VALUE1);
        $b = new \jarekkozak\tests\dict\Dict1(\jarekkozak\tests\dict\Dict1::VALUE1);
        $this->assertTrue($a->value() == $b->value());



    }
}