<?php

namespace jarekkozak\dict;

use jarekkozak\tests\dict\Dict1;
use jarekkozak\tests\dict\Dict1Translator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-26 at 11:25:19.
 */
class DictionarySelectDecoratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DictionarySelectDecorator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers jarekkozak\dict\DictionarySelectDecorator::values
     */
    public function testValues()
    {
        $comp = [
            1 => Dict1::VALUE1,
            2 => Dict1::VALUE2
        ];
        $decorator = new DictionarySelectDecorator();
        self::assertEquals($comp, $decorator->values(Dict1::getInstance()->values()));
    }

    /**
     * With translation
     * @covers jarekkozak\dict\DictionarySelectDecorator::values
     */
    public function testValuesTrans()
    {
        $comp = [
            1 => Dict1::VALUE1.'-TRANSLATED-jarekkozak\tests\dict\Dict1',
            2 => Dict1::VALUE2.'-TRANSLATED-jarekkozak\tests\dict\Dict1'
        ];
        $decorator = new DictionarySelectDecorator(new Dict1Translator());
        self::assertEquals($comp, $decorator->values(Dict1::getInstance()->values()));
    }
}