<?php

namespace jarekkozak\dict;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-25 at 16:20:53.
 */
class EnumSelectDecoratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var EnumSelectDecorator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jarekkozak\dict\EnumSelectDecorator::values
     * @todo   Implement testValues().
     */
    public function testValues()
    {
        $b = \jarekkozak\tests\dict\EnumMock::getInstance();
        $a  = EnumSelectDecorator::values($b);

        $comp = [
            1=>'A',
            2=>'B',
            null=>'NONE'
        ]

    }

    /**
     * @covers jarekkozak\dict\EnumSelectDecorator::jsonValues
     * @todo   Implement testJsonValues().
     */
    public function testJsonValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}