<?php

namespace jarekkozak\dict;

use jarekkozak\tests\dict\EnumMock;
use jarekkozak\tests\dict\EnumMock1;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-25 at 15:14:07.
 */
class EnumTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Enum
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jarekkozak\dict\Enum::values
     * @todo   Implement testValues().
     */
    public function testValues()
    {
        self::assertCount(3,  EnumMock::values());
        self::assertCount(4,  EnumMock1::values());
    }

    /**
     * @covers jarekkozak\dict\Enum::isValid
     */
    public function testIsValid()
    {
        self::assertTrue(EnumMock::isValid(1));
        self::assertTrue(EnumMock::isValid(2));
        self::assertFalse(EnumMock::isValid('1'));
        self::assertFalse(EnumMock::isValid(3));

        self::assertTrue(EnumMock1::isValid('1'));
        self::assertTrue(EnumMock1::isValid('2'));
        self::assertFalse(EnumMock1::isValid(1));
        self::assertTrue(EnumMock1::isValid('3'));
    }

    /**
     * @covers jarekkozak\dict\Enum::name
     */
    public function testName()
    {
        self::assertEquals('A',EnumMock::name(1));
        self::assertEquals(FALSE,EnumMock::name('1'));
        self::assertEquals('C1',EnumMock1::name('3'));
        self::assertEquals(FALSE,EnumMock1::name(3));
    }

    /**
     * @covers jarekkozak\dict\Enum::value
     */
    public function testValue()
    {
        self::assertEquals(1,EnumMock::value('A'));
        self::assertEquals(NULL,EnumMock::value('A1'));
    }

    public function testEnumName(){
        self::assertEquals('jarekkozak\tests\dict\EnumMock', EnumMock::enumName());
    }

    public function testGetInstance(){
        self::assertInstanceOf('jarekkozak\tests\dict\EnumMock', EnumMock::getInstance());
        self::assertInstanceOf('jarekkozak\tests\dict\EnumMock1', EnumMock1::getInstance());
    }
}