<?php

namespace jarekkozak\helpers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-12 at 13:31:26.
 */
class FlashHelperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FlashHelper
     */

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jarekkozak\helpers\FlashHelper::setFlashSuccess
     * @todo   Implement testSetFlashSuccess().
     */
    public function testSetFlashSuccess()
    {
        $message = 'Success Message';
        $this->assertFalse(FlashHelper::hasFlashSuccess());
        FlashHelper::setFlashSuccess($message);
        $this->assertTrue(FlashHelper::hasFlashSuccess());
    }


    /**
     * @covers jarekkozak\helpers\FlashHelper::setFlashInfo
     */
    public function testSetFlashInfo()
    {
        $message = 'Success Message';
        $this->assertFalse(FlashHelper::hasFlashInfo());
        FlashHelper::setFlashInfo($message);
        $this->assertTrue(FlashHelper::hasFlashInfo());
    }


    /**
     * @covers jarekkozak\helpers\FlashHelper::setFlashError
     */
    public function testSetFlashError()
    {
        $message = 'Success Message';
        $this->assertFalse(FlashHelper::hasFlashError());
        FlashHelper::setFlashError($message);
        $this->assertTrue(FlashHelper::hasFlashError());
    }

    /**
     * @covers jarekkozak\helpers\FlashHelper::setFlashWarning
     */
    public function testSetFlashWarning()
    {
        $message = 'Success Message';
        $this->assertFalse(FlashHelper::hasFlashWarning());
        FlashHelper::setFlashWarning($message);
        $this->assertTrue(FlashHelper::hasFlashWarning());
    }

    
    /**
     * @covers jarekkozak\helpers\FlashHelper::setFlashDanger
     */
    public function testSetFlashDanger()
    {
        $message = 'Success Message';
        $this->assertFalse(FlashHelper::hasFlashDanger());
        FlashHelper::setFlashDanger($message);
        $this->assertTrue(FlashHelper::hasFlashDanger());
    }

    /**
     * @covers jarekkozak\helpers\FlashHelper::setFlashPrimary
     * @todo   Implement testSetFlashPrimary().
     */
    public function testSetFlashPrimary()
    {
        $message = 'Success Message';
        $this->assertFalse(FlashHelper::hasFlashPrimary());
        FlashHelper::setFlashPrimary($message);
        $this->assertTrue(FlashHelper::hasFlashPrimary());
    }

}