<?php

namespace jarekkozak\kie;

use jarekkozak\kie\converters\KieMomentConverter;
use jarekkozak\kie\heartbeat\KieHBRequest;
use Moment\Moment;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-06 at 08:31:00.
 */
class KieContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var KieContainer
     */
    protected $object;
    protected $property;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->property = new \jarekkozak\sys\PropertiesFile([
            'filename' => '$HOME/.secret/kiesrv-secret'
        ]);
        if ($this->property->getProperty('kie-server') == NULL) {
            echo 'Property file does not exist:';
            echo 'With content:';
            echo 'kie-server=exchange_address_with_context';
            echo 'kie-user=username or email';
            echo 'kie-password=password';
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Creates KIE client
     * @return \jarekkozak\kie\KieClient
     */
    public function getClient()
    {
        $client = new KieClient([
            'context' => $this->property->getProperty('kie-server'),
            'username' => $this->property->getProperty('kie-user'),
            'password' => $this->property->getProperty('kie-password'),
        ]);
        return $client;
    }

    /**
     * @covers jarekkozak\kie\KieContainer::getContainerInfo
     * @todo   Implement testGetContainerInfo().
     */
    public function testGetContainerInfo()
    {
        $client    = $this->getClient();
        $container = new KieContainer([
            'client' => $client,
            'container' => 'containers/heartbeat'
        ]);
        $info      = $container->getContainerInfo();
    }

    public function testExecute()
    {
        $client    = $this->getClient();
        $container = new KieContainer([
            'client' => $client,
            'container' => 'containers/heartbeat'
        ]);
///
        $batch     = new KieBatch(['lookup' => 'ksession']);
        $converter = new KieMomentConverter();
        $config    = ['factName' => 'trimetis.heartbeat.Request', 'nodes' => [
                'message',
                'start' => [
                    'name' => 'start',
                    'converter' => $converter,
                ],
                'time' => [
                    'converter' => $converter,
                ]
            ],
        ];

        $request          = new KieHBRequest();
        $request->message = 'Test Message';
        $request->start   = new Moment('2015-01-01T12:34:00');
        $request->time    = new Moment('2015-01-02T12:34:00');

        $config['identifier'] = 'request1';

        $reqFact1 = new KieFact($request,$config);


        $batch->addFact($reqFact1);

        $batch->addQuery(new KieQuery([
            'name' => 'getResponse',
            'identifier' => 'response'
        ]));

///
        $res     = $container->execute($batch);
        $this->assertTrue($res);
        $results = $container->getResults();
        $this->assertCount(2, $results);
    }
}