<?php

namespace jarekkozak\kie;

use Httpful\Mime;
use Httpful\Request;
use Httpful\Response;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-05 at 12:29:44.
 */
class KieClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var KieClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new KieClient;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }


    /**
     * Test Client
     */
    public function testContainerInfo()
    {
        $client = new KieClient([
            'context'=>'http://localhost:8081/kie-server',
            'username'=>'kiesrv',
            'password'=>'kiesrv',
        ]);

        $exp = [
          'version' => '6.2.0.Final'
        ];
        $result = $client->getServerInfo();
        $this->assertEquals($exp, $result);
        $this->assertTrue($client->isOk());

    }
}