<?php

namespace jarekkozak\kie;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-19 at 08:26:30.
 */
class XMLTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var XML
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new XML;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jarekkozak\kie\XML::parse
     * @todo   Implement testParse().
     */
    public function testParse()
    {
        $parser = new XML();
        $parser->parse(__DIR__.'/test.xml');
    }
}